query Collections {  
  collections {
    id
    title
    content
    content_two
    content_image {
      url
    }
    SEOmetaData {
      metaTitle
      metaDescription
      shareImage {
        media { url }
      }
    }
  }
}