query Collections($id: ID!) {
  collection(id: $id) {
    id
    title
    content
    content_two
    content_image { url }
    # SEOmetaData {
    #   metaTitle
    #   metaDescription
    #   shareImage {
    #     media { url }
    #   }
    # }
  }
}